added rename function
ONLYOFFICE/onlyoffice-humhub pull request #80
Opened 2022-04-18 14:15 UTC by NTyan

Added rename function to editor

2022-04-19 14:24 UTC, Antipkin-A approved these changes

2022-04-22 08:49 UTC, LinneyS requested changes

2022-04-22 08:49 UTC, LinneyS commented on controllers/ApiController.php
> +        $file = File::findOne(['onlyoffice_key' => $data['key']]);
change the order:
1) renaming
2) send command `meta`

2022-04-22 08:49 UTC, LinneyS commented on controllers/ApiController.php
> +                "title" => $data['newFileName']
Send name with extension

2022-04-22 08:49 UTC, LinneyS commented on resources/humhub.onlyoffice.js
> +            'onMetaChange': onMetaChange,
Remove not used event

2022-04-22 08:49 UTC, LinneyS commented on controllers/ApiController.php
> +        $file->updateAttributes(['file_name' => $data['newFileName'] . "." . $ext]);
Check access right

2022-08-01 12:42 UTC, merged